runtime: nodejs22
env: standard
instance_class: F1

automatic_scaling:
  max_instances: 2

env_variables:
  NODE_ENV: "production"
  DB_HOST: "/cloudsql/cpd-ca1-praveen:europe-west2:client-db-instance"
  DB_PORT: "5432"
  DB_NAME: "clientdb"
  DB_USER: "clientuser"
  # DB_PASSWORD comes from Secret Manager (not here)

beta_settings:
  cloud_sql_instances: cpd-ca1-praveen:europe-west2:client-db-instance
