runtime: nodejs22
instance_class: F1
env: standard

automatic_scaling:
  target_cpu_utilization: 0.65
  target_throughput_utilization: 0.75
  max_instances: 2

env_variables:
  NODE_ENV: production
  DB_HOST: "/cloudsql/cpd-ca1-praveen:europe-west2:client-db-instance"
  DB_PORT: "5432"
  DB_NAME: "clientdb"
  DB_USER: "clientuser"
  DB_PASSWORD: "PKcloud@202629"

beta_settings:
  cloud_sql_instances: cpd-ca1-praveen:europe-west2:client-db-instance
